### ISSUE TITLE
Errors using require() and import

### ISSUE THREAD

**Issue by omundy** [alsey/nodejs-mysql#2]
I [encountered issues](https://stackoverflow.com/questions/77621581/astro-static-build-fails-when-using-certain-node-packages) attempting to use this project inside two different projects (Astro as well as Express). You may make notes about potential project or archive so it doesn't happen to someone else. 

Bare bones example. While connection works on its own, exporting it as a module fails. This will generate `TypeError: mysql.getInstance is not a function` error.

```js
// server.js
(async function () {
  var MySQLData = require('./mysql-data.js')
  let data = await MySQLData.getData()
  console.log(data)
})()
```

```js
// mysql-data.js
var mysql = require('nodejs-mysql')

exports.getData = async () => {
  const config = {
    host: 'localhost',
    port: 3306,
    user: 'root',
    password: '',
    database: 'db_name',
  }

  const db = mysql.getInstance(config)
  let data
  await db
    .exec('select * from table_name')
    .then((rows) => (data = rows))
    .catch((err) => console.warn(err))
  return data
}
```
